Repository Task-Force-Raider/Liberation-Livonia, pull requests merged in 2019-11, with the labels that each got.

#13 Update UCR_setup.sqf
  kp_liberation.Enoch/INC_undercover/UCR_setup.sqf
Labels: enhancement

#18 Update mission.sqm
  kp_liberation.Enoch/mission.sqm
Labels: enhancement

#20 Update CODEOWNERS
  CODEOWNERS
Labels: documentation

#21 Create README.md
  README.md
Labels: documentation

#25 Update README.md
  README.md
Labels: documentation

#26 Commander Whitelist
  README.md
  kp_liberation.Enoch/ui/mission_params.hpp
  kp_liberation.Enoch/whitelist.sqf
Labels: documentation

#27 Updated mission.sqm
  kp_liberation.Enoch/INC_undercover/UCR_setup.sqf
  kp_liberation.Enoch/mission.sqm
Labels: do not merge, enhancement
